/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "on-error": "#ffffff",
        "on-tertiary-container": "#fffbff",
        "inverse-surface": "#213145",
        "on-primary": "#ffffff",
        "primary-container": "#2170e4",
        "on-secondary-container": "#00714d",
        "tertiary": "#924700",
        "primary-fixed-dim": "#adc6ff",
        "on-error-container": "#93000a",
        "tertiary-container": "#b75b00",
        "surface-variant": "#d3e4fe",
        "on-primary-fixed": "#001a42",
        "tertiary-fixed": "#ffdcc6",
        "surface-container-low": "#eff4ff",
        "surface-bright": "#f8f9ff",
        "secondary-container": "#6cf8bb",
        "on-background": "#0b1c30",
        "on-surface-variant": "#424754",
        "secondary-fixed": "#6ffbbe",
        "on-primary-fixed-variant": "#004395",
        "on-tertiary-fixed-variant": "#723600",
        "secondary": "#006c49",
        "primary-fixed": "#d8e2ff",
        "surface-container": "#e5eeff",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#fefcff",
        "tertiary-fixed-dim": "#ffb786",
        "surface-tint": "#005ac2",
        "surface-container-high": "#dce9ff",
        "on-tertiary": "#ffffff",
        "primary": "#0058be",
        "background": "#f8f9ff",
        "surface-container-highest": "#d3e4fe",
        "secondary-fixed-dim": "#4edea3",
        "outline-variant": "#c2c6d6",
        "on-secondary-fixed": "#002113",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "on-surface": "#0b1c30",
        "on-secondary-fixed-variant": "#005236",
        "inverse-on-surface": "#eaf1ff",
        "on-tertiary-fixed": "#311400",
        "outline": "#727785",
        "inverse-primary": "#adc6ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "sm": "12px",
        "lg": "40px",
        "base": "8px",
        "margin": "32px",
        "gutter": "24px",
        "md": "24px",
        "xl": "64px"
      },
      fontFamily: {
        "display-lg": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "body-compact": ["Inter", "sans-serif"],
        "title-sm": ["Inter", "sans-serif"],
        "body-main": ["Inter", "sans-serif"],
        "mono-data": ["monospace"],
        "headline-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["36px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-compact": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "title-sm": ["18px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-main": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "mono-data": ["14px", { lineHeight: "1.4", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
